name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Set git to use LF
        run: | # (eslint complains otherwise)
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

          
      - name: download LayoutEngine and associated chrome version
        run: bash .github/workflows/Download_LayoutEngine.sh

      - name: (Linux) Ensure specific chrome version is installed
        if: ${{ matrix.os == 'ubuntu-latest' }} 
        run: |
            # uninstall chrome:
            sudo apt purge google-chrome-stable -y
            rm -rf ~/.config/google-chrome

            # install specific version:
            sudo apt install ./tools/google-chrome-stable.deb

            # print version
            google-chrome --version
      - name: (Windows) Ensure specific chrome version is installed
        if: ${{ matrix.os == 'windows-latest' }} 
        run: |
            # uninstall default version
            wmic product where "name like 'Google Chrome'" call uninstall /nointeractive
            
            # install specific version:
            tools\google-chrome-standalone.exe /install
            
            # print version
            (Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test --ci --maxWorkers=1 --silent=false
        timeout-minutes: 3
        
      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
