name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Ensure latest chrome version is installed (docker image can be out-of-date) (Windows)
        if: ${{ matrix.os == 'windows-latest' }} 
        run: |
          choco upgrade googlechrome -y --version=95.0.4638.54 --ignore-checksums

      - name: download LayoutEngine
        run: bash .github/workflows/Download_LayoutEngine.sh

      - name: Test
        run: yarn test --ci --maxWorkers=2 --silent=false
        timeout-minutes: 3
        
      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
